### ISSUE TITLE
Build Session - cannot always remove or edit session item

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#16]
On the Build a Session page - 
A session item can be edited or removed by "swiping" the item - but, only after 1st adding the item.

The item cannot always be "swiped" - to edit or remove the item - when:
- editing a saved session or modifying the default session that is first displayed when creating a new session
For some saved sessions, you can swipe & for others you cannot not.

**Comment by gshotwell** [comment]
I think this is a bug with the swipe-list view, it sometimes gets stuck and the row kind of opens a tiny bit but then bounces back. It can be resolved by scrolling or changing the list.

**Comment by chrismorel** [comment]
Yes, if I scroll up (or down) ... sometimes multiple times ... it does open the swipe-list view.

Can the rows be automatically re scrolled on the initial display of the session - would that help (as a workaround fix)?

**Comment by chrismorel** [comment]
Will this be a priority to be done for this release?  Maybe, there is an update for the swipe-list view, itself?  (React Native)

**Comment by gshotwell** [comment]
Yeah, you're right is is a kind of annoying issue. This is being triggered by the scroll-to-bottom functionality and doesn look like it's an active bug in [swipelistview](https://github.com/jemise111/react-native-swipe-list-view/issues/109) The workaround I came up with is to make the rows open when they are pressed. This is still a bug because swiping doesn't work, but I think it's probably one we can live with. What do you think?

**Comment by chrismorel** [comment]
Sounds like an OK workaround/fix.  Will try it in the next update.

**Comment by chrismorel** [comment]
Just tested it.  Seems look a good solution.
